# Generated by Django 4.2 on 2025-02-12 21:34

from django.contrib.auth.models import Group
from django.db import migrations


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name="Comum")
    Group.objects.get_or_create(name="Administrador")


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
