# Generated by Django 4.2 on 2025-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='car_model',
            field=models.ManyToManyField(blank=True, related_name='parts', to='app.carmodel'),
        ),
    ]
